title: Helsa Chan
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my page! Thanks for visiting!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: helsachan
github_username:  helsachan
github: [metadata]
logo: "/apple-touch-icon.png"

# Build settings
locale: "en-US"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dirt"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
repository: helsachan/helsachan.github.io
include: ["_pages", "_category"]

# Customization
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      show_date: true
      layout: posts
  - scope:
      path: ""
      type: portfolio
    values:
      read_time: false
      show_date: true
      layout: posts
      
breadcrumbs: true
comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
masthead_title: "Helsa Chan -- I make cakes..."
permalink: "/:categories/:title/"
search: true